import { validateFormula } from '../../features/formula-editor/formulaValidator';
import { parseFormulaDsl } from '../../features/formula-editor/formulaParser';
test('accepts linear aggregate constraint',()=>expect(validateFormula('sum(p[u,t] for u in unit) >= load[t]','constraint').valid).toBe(true));
test('rejects unsupported relation',()=>expect(validateFormula('p[t] != load[t]','constraint').valid).toBe(false));
test('rejects incomplete relation expressions',()=>{expect(validateFormula('p[t] >=','constraint').errors).toContain('关系符左右两侧都必须填写表达式');expect(validateFormula('<= load[t]','constraint').errors).toContain('关系符左右两侧都必须填写表达式')});
test('validates referenced objects, indices, and foreach scope',()=>{const symbols={sets:{unit:'机组',time:'时段'},parameters:{load:{label:'负荷',indices:['time']}},variables:{p:{label:'出力',indices:['unit','time']}}};const tokens=[{type:'variable' as const,code:'p',label:'出力',indices:['unit','time'],indexAliases:['u','t']},{type:'operator' as const,code:'<=',label:'<='},{type:'parameter' as const,code:'load',label:'负荷',indices:['time'],indexAliases:['t']}];expect(validateFormula('p[u,t] <= load[t]','constraint',tokens,symbols,['unit','time']).valid).toBe(true);expect(validateFormula('p[u,t] <= load[t]','constraint',tokens,symbols,['time']).errors).toContain('自由索引未被作用范围覆盖：unit')});
test('rejects missing context objects',()=>{const tokens=[{type:'variable' as const,code:'missing_p',label:'缺失变量',indices:['time'],indexAliases:['t']}];expect(validateFormula('missing_p[t] <= 1','constraint',tokens,{sets:{time:'时段'},parameters:{},variables:{}},['time']).errors).toContain('引用变量不存在：missing_p')});
test('does not treat a longer parameter name as a repeated variable',()=>{const dsl='sum(deviation_penalty[t] * deviation_penalty_price * delta_t for t in time)';const symbols={sets:{time:'时段'},parameters:{deviation_penalty_price:{label:'偏差考核单价'},delta_t:{label:'时间步长'}},variables:{deviation_penalty:{label:'超限偏差',indices:['time']}}};const tokens=parseFormulaDsl(dsl,symbols);expect(validateFormula(dsl,'objective',tokens,symbols,[]).valid).toBe(true)});
test('known function names are not reported as missing parameters',()=>{const dsl='abs(p[t]) <= load[t]';const symbols={sets:{time:'时段'},parameters:{load:{label:'负荷',indices:['time']}},variables:{p:{label:'出力',indices:['time']}}};const tokens=parseFormulaDsl(dsl,symbols);const result=validateFormula(dsl,'constraint',tokens,symbols,['t']);expect(result.errors).not.toContain('引用参数不存在：abs')});
